ControloDeCompras/Models/ErrorViewModel.cs
namespace ControloDeCompras.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ControloDeCompras/Models/ShoppingList.cs
using System.ComponentModel.DataAnnotations;

namespace ControloDeCompras.Models
{
    public class ShoppingList
    {
        [Key]
        public int Id { get; set; }


        [Required(ErrorMessage = "O genero é de preenchimento obrigatório.")]
        public string Genero { get; set; } = null!;


        public string? Nome { get; set; } = null!;


        public string? Variedade { get; set; } = null!;


        [Required(ErrorMessage = "A quantidade é de preenchimento obrigatório.")]
        public int Quantidade { get; set; }


        [Display(Name = "Preço")]
        public double? Preco { get; set; }

    }
}

ControloDeCompras/Controllers/HomeController.cs
using ControloDeCompras.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ControloDeCompras.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SobreNos()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ControloDeCompras/Controllers/ShoppingListController.cs
using ControloDeCompras.Data;
using ControloDeCompras.Models;
using Microsoft.AspNetCore.Mvc;

namespace ControloDeCompras.Controllers
{
    public class ShoppingListController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ShoppingListController(ApplicationDbContext bd) /*injetar serviços*/
        {
            _db = bd;
        }

        public IActionResult Index()
        {
            IEnumerable<ShoppingList> objShoppingList = _db.ShoppingLists;

            return View(objShoppingList);
        }

        // Get
        public IActionResult Create()
        {
            return View();
        }

        // Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ShoppingList obj)
        {
            if(obj.Genero == obj.Nome)
            {
                ModelState.AddModelError("Genero", "Os campos Genero e Nome não podem ter o mesmo valor.");
            }

            if (ModelState.IsValid)
            {
                _db.ShoppingLists.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
    }
}

ControloDeCompras/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Bemvindo";
}


    <div class="container p-3">
    <div class="row justify-content-between">
        <div class="col-9">
            <h3 class="text-info">Bem vindo ao último sitio que vai precisar para gerir as suas compras</h3>
        </div>
        <div class="col-3">
            <h5 class="text-info">Conecte-se connosco.</h5>

            <button type="button" class="btn btn-success">Entrar</button>
            <button type="button" class="btn btn-success">Registar-se</button>
        </div>
    </div>
    </div>

<div class="text-center">    
    <hr />

    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="/imagens/lidl-logo.jpg" class="d-block w-100" alt="Logotipo do Lidl">
            </div>
            <div class="carousel-item">
                <img src="imagens/intermarche-logo.jpg" class="d-block w-100" alt="Logotipo do Intermarché">
            </div>
            <div class="carousel-item">
                <img src="imagens/pingo-doce-logo.jpg" class="d-block w-100" alt="Logotipo do Pingo Doce">
            </div>
            <div class="carousel-item">
                <img src="imagens/continente-logo.jpg" class="d-block w-100" alt="Logotipo do Continente">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>

    <div class="container text-center" style="margin-top:20px">
        <div class="row">
            <div class="col">
                <div class="card border-info mb-3" style="max-width: 20rem;">
                    <div class="card-header">Avaliação do cliente</div>
                    <div class="card-body">
                        <figure class="text-end">
                            <blockquote class="blockquote">
                                <p class="mb-0">O melhor site para a gestão de compras que já usei!</p>
                            </blockquote>
                            <figcaption class="blockquote-footer">
                                Criador do site em <cite title="Source Title">Pessoa</cite>
                            </figcaption>
                        </figure>
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card border-info mb-3" style="max-width: 20rem;">
                    <div class="card-header">Avaliação do cliente</div>
                    <div class="card-body">
                        <figure class="text-end">
                            <blockquote class="blockquote">
                                <p class="mb-0">Sem dúvida o melhor site para a gestão de compras na internet!!</p>
                            </blockquote>
                            <figcaption class="blockquote-footer">
                                Criador do site em <cite title="Source Title">Os sonhos que teve ontem</cite>
                            </figcaption>
                        </figure>
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card border-info mb-3" style="max-width: 20rem;">
                    <div class="card-header">Avaliação do cliente</div>
                    <div class="card-body">
                        <figure class="text-end">
                            <blockquote class="blockquote">
                                <p class="mb-0">Quase que perdi os sentidos quando encontrei esta maravilha da intranet.</p>
                            </blockquote>
                            <figcaption class="blockquote-footer">
                                Criador do site em <cite title="Source Title">Pensamentos numa sanita</cite>
                            </figcaption>
                        </figure>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

ControloDeCompras/Views/Home/SobreNos.cshtml
@{
    ViewData["Title"] = "Sobre nós";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h3 class="text-info">@ViewData["Title"]</h3>
        </div>
    </div>
</div>
@*<h1 align="center">@ViewData["Title"]</h1>*@

<div>
    <p>Estamos dedicados em criar uma ferramenta para si de forma que possa melhor controlar as suas compras e a confirmar quais os custos de cada sessão de compras. Isto porque como já se tem visto nos diversos canais de informação, os valores apresentados em caixa, nem sempre estão certos com os valores apresentados nas prateleiras.</p>
    <p>Numa segunda fase iremos ampliar esta ferramenta de modo a incorporar os valores dos diversos artigos nos supermercados de acordo com os dados introduzidos por si e todos os utilizadores na sua zona e pais.</p>
    <p>Contamos com a sua ajuda para podermos continuar a melhorar a nossa ferramenta e a poder mantê-la livre de custos para si. Para tal, contamos com as suas sugestões para melhoramentos e possíveis alterações.</p>
    <p>Também contamos com o seu contributo e para tal criamos uma conta para doações tendo como valor mínimo 0,01€</p>
    <p>Agradecemos o seu patrocínio e sugestões.</p>
</div>
<div class="text-center">
    <img class="img-fluid" src="~/imagens/thank-you-poster.jpg" alt="imagem de agradecimento" />
</div>

ControloDeCompras/Views/Shared/_Favicons.cshtml
@{
    <link rel="apple-touch-icon" sizes="180x180" href="/imagens/faviconimg/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/imagens/faviconimg/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/imagens/faviconimg/favicon-16x16.png">
    <link rel="manifest" href="/imagens/faviconimg/site.webmanifest">
    <link rel="mask-icon" href="/imagens/faviconimg/safari-pinned-tab.svg" color="#5bbad5">
    <link rel="shortcut icon" href="/imagens/faviconimg/favicon.ico">
<meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-config" content="/imagens/faviconimg/browserconfig.xml">
<meta name="theme-color" content="#ffffff">
}

ControloDeCompras/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controlo de compras</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.2.3/slate/bootstrap.min.css" integrity="sha512-GixPbJydZH3yyD23SgcC/i/FIhLb+0F26ABBvEg9ejj90hYuXXjPphWTWTX5dIuolObna6iXz1nr5nog6Dex7w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ControloDeCompras.styles.css" asp-append-version="true" />

    @Html.Partial("_Favicons")
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="/imagens/shopping-basket.png" height="60px" /></a>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ControloDeCompras</a>
                <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">                        
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="SobreNos">Sobre nós</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="ShoppingList" asp-action="Index">Lista de Compras</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ControloDeCompras
        </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js" integrity="sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ControloDeCompras/Views/ShoppingList/Create.cshtml
@model ShoppingList

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h3 class="text-info">Adicionar artigo</h3>
            <hr />
        </div>

        <div class="mb-3">
            <label asp-for="Genero"></label>
            <input asp-for="Genero" class="form-control" placeholder="Sumo / Carne / Detergente / Vinho / Fruta..." />
            <span asp-validation-for="Genero" class="text-warning"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Nome"></label>
            <input asp-for="Nome" class="form-control" placeholder="Coca Cola / Porco / Superpop / Reguengos / Tomate..." />
            <span asp-validation-for="Nome" class="text-warning"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Variedade"></label>
            <input asp-for="Variedade" class="form-control" placeholder="1,75 / Febras / Ultra Concentrado / Reserve 2020 T / Coração de Boi" />
            <span asp-validation-for="Variedade" class="text-warning"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Quantidade"></label>
            <input asp-for="Quantidade" class="form-control" placeholder="2 / 1 / 5 / 15 " />
            <span asp-validation-for="Quantidade" class="text-warning"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Preco"></label>
            <input asp-for="Preco" class="form-control" placeholder="2,15 / 3,99 / 4,73 / 20,45" />
            <span asp-validation-for="Preco" class="text-warning"></span>
        </div>

        <button type="submit" class="btn btn-success">Adicionar</button>
        <a asp-controller="ShoppingList" asp-action="Index" class="btn btn-danger">Voltar</a>
    </div>

</form>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

ControloDeCompras/Views/ShoppingList/Index.cshtml
@model IEnumerable<ShoppingList>

@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
            <div class="col-6">
                <h3 class="text-info">Lista de compras</h3>
            </div>
        <div class="col-6 text-end">
            <a asp-controller="ShoppingList" asp-action="Create" class="btn btn-success">Novo artigo</a>
            </div>
    </div>
</div>
<table class="text-center text-dark table-responsive table-sm table table-success table-hover table align-middle" style="width:100%;">
    <thead>
        <tr>
            <th>Género</th>
            <th>Nome</th>
            <th>Variedade</th>
            <th>Quantidade</th>
            <th>Preço</th>
        </tr>
    </thead>
    <tbody>
        @foreach (ShoppingList obj in Model)
        {
            <tr>
                <td>@obj.Genero</td>
                <td>@obj.Nome</td>
                <td>@obj.Variedade</td>
                <td>@obj.Quantidade</td>
                <td>@obj.Preco</td>
            </tr>
        }
        <tr>
            <td colspan="3"></td>
            <td>total:</td>
            <td>@Model.Sum(soma=>soma.Preco)</td>
        </tr>
    </tbody>
</table>